default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        exclude: "(\\.drawio)$"
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
        args: ["--maxkb=1000", "--enforce-all"]
        exclude: .github/actions/release-please/dist/index.js
      - id: detect-private-key

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
        name: upgrade code

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        name: format docstrings
        args: [--in-place, --wrap-summaries=88, --wrap-descriptions=88]

  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        name: remove unused noqa
        additional_dependencies:
          - flake8-pytest-style
          - flake8-bandit
          - flake8-simplify
          - flake8-return

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: format imports

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        name: format code

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        name: format docs
        args: [--line-length=88]
