apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Name of the ClusterRole
  name: eks-role
rules:
- apiGroups: [""]
  # This allows access to core resources such as pods, services, etc.
  resources: ["pods", "services", "namespaces"]
  verbs: ["get", "list", "create", "delete", "update", "patch"]
- apiGroups: ["apps"]
  # This allows access to applications-related resources
  resources: ["deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list", "create", "delete", "update", "patch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  # This allows access to role-based access control resources
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "create", "delete", "update", "patch"]

