services:
  api:
    build:
      context: .
      args:
        POETRY_WITH: test
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    restart: always
    volumes:
      - "./src/connectai:/app/src/connectai"
    depends_on:
      - localstack
      - redis
      - keycloak
    links:
      - localstack
      - keycloak
    networks:
      - genie_llm_internal_proxy_network
      - genie_llm_proxy_network

  test:
    profiles: ['test']
    build:
      context: .
      target: test
      args:
        POETRY_WITH: test
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - "localstack"
    links:
      - "localstack"
    networks:
      - genie_llm_internal_proxy_network


  db_init:
    build:
      context: .
      target: dbinit
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - "localstack"
    links:
      - "localstack"
    networks:
      - genie_llm_internal_proxy_network

  eval:
    profiles: ['eval']
    build:
      context: .
      args:
        POETRY_WITH: eval
      target: eval
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - "localstack"
    links:
      - "localstack"
    networks:
      - genie_llm_internal_proxy_network

  localstack:
    image: localstack/localstack:3.4.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./docker/localstack/volume}:/var/lib/localstack"
    networks:
      - genie_llm_internal_proxy_network
      - genie_llm_proxy_network

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: http://localstack:4566
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - "localstack"
    networks:
      - genie_llm_internal_proxy_network

  redis:
    image: redis:7.2.5-alpine3.20
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    networks:
      - genie_llm_internal_proxy_network

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: INFO
    volumes:
      - "./docker/keycloak:/opt/keycloak/data"
    networks:
      - genie_llm_internal_proxy_network
      - genie_llm_proxy_network

volumes:
  cache:
    driver: local

networks:
  genie_llm_proxy_network:
    driver: bridge
    name: genie_llm_proxy_network
  genie_llm_internal_proxy_network:
    driver: bridge
    name: genie_llm_internal_proxy_network
