FROM registry.access.redhat.com/ubi9 AS ubi-micro-build
RUN mkdir -p /mnt/rootfs
RUN dnf install --installroot /mnt/rootfs jq curl \
    --releasever 9 --setopt install_weak_deps=false --nodocs -y; \
    dnf --installroot /mnt/rootfs clean all

RUN ls -la /mnt/rootfs

FROM quay.io/keycloak/keycloak:24.0.3
COPY --from=ubi-micro-build /mnt/rootfs /

CMD ["start-dev", "--import-realm"]
