name: Build and Deploy to EKS

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image to Amazon ECR
      run: |
        IMAGE_URI=${{ secrets.ECR_REPO_URI }}:latest
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}

    - name: Set up kubectl
      uses: aws-actions/eks-kubeconfig-action@v1
      with:
        cluster_name: ${{ secrets.CLUSTER_NAME }}

    - name: Deploy to EKS
      run: |
        kubectl set image deployment/my-app my-app=$IMAGE_URI
        kubectl rollout status deployment/my-app

    - name: Clean up old Docker images
      run: |
        docker system prune -af