name: Evaluation Framework
on:
  push:
    branches:
      - "feature/llm/*"
      - "main"

permissions: read-all

jobs:
  build-and-run-evaluation-framework:
    runs-on: ubuntu-latest
    env:
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION_ATLAS }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_REGION_ATLAS }}
      ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DB_INIT_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DB_INIT_AWS_SECRET_ACCESS_KEY }}
      EVALUATION_OPENAI_BASE_URL: ${{ vars.EVALUATION_OPENAI_BASE_URL }}
      EVALUATION_OPENAI_API_KEY: ${{ secrets.EVALUATION_OPENAI_API_KEY }}
      EVALUATION_OPENAI_ORGANIZATION: ${{ vars.EVALUATION_OPENAI_ORGANIZATION }}
      DATA_ENVIRONMENT: develop

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -f Dockerfile --target eval --build-arg POETRY_WITH=eval . -t eval

    - name: Run Evaluation Framework
      run: |
        docker run --name eval_container \
          -e OPENAI_KEY=${{ secrets.OPENAI_KEY }} \
          -e AWS_REGION=${{ env.AWS_REGION }} \
          -e AWS_DEFAULT_REGION=${{ env.AWS_DEFAULT_REGION }} \
          -e ABLY_API_KEY=${{ secrets.ABLY_API_KEY }} \
          -e SAGEMAKER_ENDPOINT_NAME=${{ vars.SAGEMAKER_ENDPOINT_NAME }} \
          -e BEDROCK_REGION=${{ vars.BEDROCK_REGION }} \
          -e SAGEMAKER_REGION=${{ vars.SAGEMAKER_REGION }} \
          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -e EVALUATION_OPENAI_BASE_URL=${{ env.EVALUATION_OPENAI_BASE_URL }} \
          -e EVALUATION_OPENAI_API_KEY=${{ secrets.EVALUATION_OPENAI_API_KEY }} \
          -e EVALUATION_OPENAI_ORGANIZATION=${{ env.EVALUATION_OPENAI_ORGANIZATION }} \
          -e S3_BUCKET_NAME=${{ vars.DWH_BUCKET_NAME }} \
          -e EXPORT_TO_S3=True \
          -e DATA_ENVIRONMENT=develop \
          eval
